### ISSUE TITLE
Support the YAML format in addition to JSON for HAR files

### ISSUE THREAD

**Issue by divdavem** [AmadeusITGroup/kassette#464]
I am opening this issue to add support for the YAML format in addition to the JSON format for HAR files.

Since version 1.4.0, kassette supports the `har` file format to store mocks, in addition to the previous now called `folder` format.

The `folder` format uses multiple files to store a single mocked request, while the `har` format allows multiple mocked requests to be stored inside the same file. With the `folder` format, it is easy to change a response body by hand, because it is stored without any change as a separate file. With the `har` format, it is much less easy to change a response body by hand, especially when the response contains quotes and is on several lines, because it is stored as a string in the JSON file with many characters escaped.

While `har` files are supposed to be in the json format, it would be handy, and that's the purpose of this issue, to also have the possibility to store `har` files in the yaml format. It would be very easy to implement with the [`yaml` npm package](https://www.npmjs.com/package/yaml), just replacing `JSON.parse` and `JSON.stringify` by `yaml.parse` and `yaml.stringify` when dealing with yaml files.

For example, here are two equivalent examples in JSON and YAML format.
It is much more convenient to read or change the content of the YAML file by hand than the corresponding JSON file:

Standard HAR file in JSON:
```json
{
    "log": {
        "version": "1.2",
        "creator": {
            "name": "kassette",
            "version": "1.5.1"
        },
        "entries": [
            {
                "startedDateTime": "2022-09-02T09:23:44.982Z",
                "time": 232.1829260000959,
                "timings": {
                    "blocked": 1.1541330004110932,
                    "dns": 0.6127319997176528,
                    "connect": 113.61475900001824,
                    "send": 0.05972499959170818,
                    "wait": 116.47908800002187,
                    "receive": 0.26248900033533573,
                    "ssl": -1
                },
                "cache": {},
                "response": {
                    "httpVersion": "HTTP/1.1",
                    "status": 200,
                    "statusText": "OK",
                    "headers": [
                        {
                            "name": "Age",
                            "value": "455313"
                        },
                        {
                            "name": "Cache-Control",
                            "value": "max-age=604800"
                        },
                        {
                            "name": "Content-Type",
                            "value": "text/html; charset=UTF-8"
                        },
                        {
                            "name": "Date",
                            "value": "Fri, 02 Sep 2022 09:23:45 GMT"
                        },
                        {
                            "name": "Etag",
                            "value": "\"3147526947+ident\""
                        },
                        {
                            "name": "Expires",
                            "value": "Fri, 09 Sep 2022 09:23:45 GMT"
                        },
                        {
                            "name": "Last-Modified",
                            "value": "Thu, 17 Oct 2019 07:18:26 GMT"
                        },
                        {
                            "name": "Server",
                            "value": "ECS (dcb/7F60)"
                        },
                        {
                            "name": "Vary",
                            "value": "Accept-Encoding"
                        },
                        {
                            "name": "X-Cache",
                            "value": "HIT"
                        },
                        {
                            "name": "Content-Length",
                            "value": "1256"
                        },
                        {
                            "name": "Connection",
                            "value": "close"
                        }
                    ],
                    "redirectURL": "",
                    "cookies": [],
                    "headersSize": -1,
                    "bodySize": 1256,
                    "content": {
                        "mimeType": "text/html; charset=UTF-8",
                        "size": 1256,
                        "text": "<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset=\"utf-8\" />\n    <meta http-equiv=\"Content-type\" content=\"text/html; charset=utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n    <style type=\"text/css\">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, \"Segoe UI\", \"Open Sans\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href=\"https://www.iana.org/domains/example\">More information...</a></p>\n</div>\n</body>\n</html>\n"
                    }
                },
                "request": {
                    "method": "GET",
                    "url": "http://example.com/",
                    "httpVersion": "HTTP/1.1",
                    "headers": [
                        {
                            "name": "Host",
                            "value": "example.com"
                        },
                        {
                            "name": "Proxy-Connection",
                            "value": "keep-alive"
                        },
                        {
                            "name": "Upgrade-Insecure-Requests",
                            "value": "1"
                        },
                        {
                            "name": "User-Agent",
                            "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.48 Safari/537.36"
                        },
                        {
                            "name": "Accept",
                            "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
                        },
                        {
                            "name": "Accept-Encoding",
                            "value": "gzip, deflate"
                        },
                        {
                            "name": "Accept-Language",
                            "value": "en-US,en;q=0.9"
                        }
                    ],
                    "cookies": [],
                    "queryString": [],
                    "headersSize": -1,
                    "bodySize": 0
                }
            }
        ]
    }
}

```

Corresponding HAR file in YAML:
```yaml
log:
  version: "1.2"
  creator:
    name: kassette
    version: 1.5.1
  entries:
    - startedDateTime: 2022-09-02T09:23:44.982Z
      time: 232.1829260000959
      timings:
        blocked: 1.1541330004110932
        dns: 0.6127319997176528
        connect: 113.61475900001824
        send: 0.05972499959170818
        wait: 116.47908800002187
        receive: 0.26248900033533573
        ssl: -1
      cache: {}
      response:
        httpVersion: HTTP/1.1
        status: 200
        statusText: OK
        headers:
          - name: Age
            value: "455313"
          - name: Cache-Control
            value: max-age=604800
          - name: Content-Type
            value: text/html; charset=UTF-8
          - name: Date
            value: Fri, 02 Sep 2022 09:23:45 GMT
          - name: Etag
            value: '"3147526947+ident"'
          - name: Expires
            value: Fri, 09 Sep 2022 09:23:45 GMT
          - name: Last-Modified
            value: Thu, 17 Oct 2019 07:18:26 GMT
          - name: Server
            value: ECS (dcb/7F60)
          - name: Vary
            value: Accept-Encoding
          - name: X-Cache
            value: HIT
          - name: Content-Length
            value: "1256"
          - name: Connection
            value: close
        redirectURL: ""
        cookies: []
        headersSize: -1
        bodySize: 1256
        content:
          mimeType: text/html; charset=UTF-8
          size: 1256
          text: >
            <!doctype html>

            <html>

            <head>
                <title>Example Domain</title>

                <meta charset="utf-8" />
                <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <style type="text/css">
                body {
                    background-color: #f0f0f2;
                    margin: 0;
                    padding: 0;
                    font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
                    
                }
                div {
                    width: 600px;
                    margin: 5em auto;
                    padding: 2em;
                    background-color: #fdfdff;
                    border-radius: 0.5em;
                    box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
                }
                a:link, a:visited {
                    color: #38488f;
                    text-decoration: none;
                }
                @media (max-width: 700px) {
                    div {
                        margin: 0 auto;
                        width: auto;
                    }
                }
                </style>    
            </head>


            <body>

            <div>
                <h1>Example Domain</h1>
                <p>This domain is for use in illustrative examples in documents. You may use this
                domain in literature without prior coordination or asking for permission.</p>
                <p><a href="https://www.iana.org/domains/example">More information...</a></p>
            </div>

            </body>

            </html>
      request:
        method: GET
        url: http://example.com/
        httpVersion: HTTP/1.1
        headers:
          - name: Host
            value: example.com
          - name: Proxy-Connection
            value: keep-alive
          - name: Upgrade-Insecure-Requests
            value: "1"
          - name: User-Agent
            value: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
              Chrome/104.0.5112.48 Safari/537.36
          - name: Accept
            value: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
          - name: Accept-Encoding
            value: gzip, deflate
          - name: Accept-Language
            value: en-US,en;q=0.9
        cookies: []
        queryString: []
        headersSize: -1
        bodySize: 0

```
